In [2]:
#예제 1
symbols = "$*&!@"
codes =[]

for symbol in symbols:
  codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


In [5]:
#예제 2
symbols = "$*&!@"

codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]


In [6]:
#예제 3
x = '"!~?$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)

"!~?$$*&!@
[34, 33, 126, 63, 36, 36, 42, 38, 33, 64]


In [15]:
#예제 4
symbols = '"!~?$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascii)


[34, 33, 126, 63, 36, 36, 42, 38, 33, 64]


In [16]:
#예제 5
symbols = '"!~?$$*&!@'
beyond_ascii = list(filter(lambda c: c > 64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function: \n>>> {map(ord, symbols)}")
print(f"List after map: \n>>> {list(map(ord, symbols))}")

[126] 

Map function: 
>>> <map object at 0x7e42b5c3e1d0>
List after map: 
>>> [34, 33, 126, 63, 36, 36, 42, 38, 33, 64]


In [18]:
#예제 6
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
  for size in sizes:
    print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [20]:
#예제 7
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [22]:
#예제 8
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in ('{} {}'.format(c, s) for c in colors for s in sizes):
  print(tshirt)

black S
black M
black L
white S
white M
white L


In [25]:
#예제 9
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
  print('%s/%s' % passport)
  print('{}/{}'.format(passport[0], passport[1]))
  print(f'{passport[0]}/{passport[1]}')


BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


In [26]:
#예제 10
for country, _ in traveler_ids:
  print(country)

USA
BRA
ESP


In [27]:
#예제 11
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates

print(latitude)
print(longitude)

33.9425
-118.408056


In [28]:
#예제 12
a = 10; b = 20
b, a = a, b
print(a, b)

20 10


In [30]:
#예제 13
divmod(20, 8)

t = (20, 8)
divmod(*t)

quotient, remainder = divmod(*t)
print(quotient, remainder)

2 4


In [32]:
#예제 14
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename



'idrsa.pub'

In [33]:
#예제 15
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [35]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [36]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [37]:
#예제 16
a, *hody, c, d = range(5)
a, hody, c, d

(0, [1, 2], 3, 4)

In [38]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [40]:
#예제 17
metro_areas = [
    ("Tokyo", "JP", 36.933, (35, 139)),
    ("D0elhi NCR", "IN", 21, (28, 77)),
    ("Mexico City", "MX", 20, (19, -99)),
    ("New York-Newark", "US", 20, (40, -74)),
    ("Sao Paulo", "BR", 19, (-23, -46))
]

print("{:15} | {:^9} | {:^9}".format("", "lat.", "long."))
fmt = "{:15} | {:9.4f} | {:9.4f}"

for name, cc, pop, (lat, long) in metro_areas:
  if long <= 0:
    print(fmt.format(name, lat, long))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [45]:
#예제 18
from collections import namedtuple
City = namedtuple('Ciry', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))
print(tokyo)
print(tokyo.population)
print(tokyo.coordinates)
print(tokyo[1])
City._fields

Ciry(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139.691))
36.933
(35.689, 139.691)
JP


('name', 'country', 'population', 'coordinates')

In [47]:
#예제 19
City._fields

('name', 'country', 'population', 'coordinates')

In [48]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))

In [49]:
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613, long=77.208)}

In [50]:
for key, value in delhi._asdict().items():
  print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [51]:
#예제 20
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [52]:
l[2:]

[30, 40, 50, 60]

In [53]:
l[:3]

[10, 20, 30]

In [54]:
l[3:]

[40, 50, 60]

In [56]:
#예제 21
invoice = """
0.....6..................25........33......40.......
1909  Pimoroni               $17.50   3      $52.50
1489  6mm Tactile            $4.95    2      $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]
for item in line_items:
  print(item[UNIT_PRICE], item[DESCRIPTION])

    $17. Pimoroni           
    $4.9 6mm Tactile        
 


In [67]:
#예제 22
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [68]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [69]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [70]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [63]:
#예제 23
l[2::5] = 100

TypeError: must assign iterable to extended slice

In [71]:
#예제 24
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [72]:
#예제 25
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [73]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [74]:
#예제 26
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [75]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [76]:
#예제 27
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [77]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [78]:
#예제 28
row = ['_'] * 3
board = []
for i in range(3):
  board.append(row)

board[1][2] = 'X'

board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [79]:
#예제 29
board = []
for i in range(3):
  row = ['_'] * 3
  board.append(row)

print(board)

board[2][0] = 'X'

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [92]:
#예제 30
ㅣ = [1,2,3]
id(ㅣ)

138824975581120

In [94]:
ㅣ *= 2
ㅣ

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [97]:
id(l)

138824971228864

In [98]:
#예제 31
t = (1, 2, 3)
id(t)

138824971290176

In [99]:
t *= 2
id(t)

138824973103744

In [109]:
#예제 32
t = (1, 2, [30, 40])
print(t)

t[2] += [50, 60]


(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [110]:
#예제 33
print(t)

(1, 2, [30, 40, 50, 60])


In [112]:
#예제 34
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [113]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [114]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [115]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [116]:
#예제 35
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [117]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [118]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [121]:
#예제 36
from array import array
from random import random

floats = array('d', (random() for _ in range(10**7)))
floats[-1]

0.8319956777421131

In [122]:
#예제 37
with open('floats.bin', 'wb') as f:
  floats.tofile(f)

In [123]:
floats2 = array('d')
with open('floats.bin', 'rb') as f:
  floats2.fromfile(f, 10**7)

floats2[-1]

0.8319956777421131

In [125]:
floats == floats2

True

In [126]:
#예제 38
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [127]:
memv[0]

-2

In [128]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [129]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [130]:
#예제 38-1
data = bytearray(b'hello world')
mv = memoryview(data)

print(mv[0])
mv[0] = 72

print(data)


104
bytearray(b'Hello world')


In [131]:
#예제 39
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [132]:
type(a)

numpy.ndarray

In [133]:
#예제 40
a.shape

(12,)

In [134]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
#예제 41
a[2]

array([ 8,  9, 10, 11])

In [137]:
print(a[2, 1])

9


In [138]:
a[:, 1]

array([1, 5, 9])

In [139]:
#예제 42
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])